import { generate as id } from "shortid";
export  const words = [
    { eng: "dog", ua: "собака", id: id() },
    { eng: "puppy", ua: "щеня", id: id() },
    { eng: "cat", ua: "кіт", id: id() },
    { eng: "kitten", ua: "кошеня", id: id() },
    { eng: "goldfish", ua: "Золота рибка", id: id() },
    { eng: "turtle", ua: "черепаха", id: id() },
    { eng: "canary", ua: "канарейка", id: id() },
    { eng: "Hamster", ua: `хом'як`, id: id() },
    { eng: "parrot", ua: "папуга", id: id() },
    { eng: "guinea pig", ua: "морська свинка", id: id() },
    { eng: "chicken", ua: "курка", id: id() },
    { eng: "rooster", ua: "півень", id: id() },
    { eng: "turkey", ua: "індичка", id: id() },
    { eng: "gobbler", ua: "індик", id: id() },
    { eng: "goat", ua: "коза", id: id() },
    { eng: "billy goat", ua: "козел", id: id() },
    { eng: "kid", ua: "козеня", id: id() },
    { eng: "sheep", ua: "вівця", id: id() },
    { eng: "ram", ua: "баран", id: id() },
    { eng: "lamb", ua: "ягня", id: id() },
    { eng: "bull", ua: "Бик", id: id() },
    { eng: "cow", ua: "корова", id: id() },
    { eng: "calf", ua: "теля", id: id() },
    { eng: "stallon", ua: "жеребек", id: id() },
    { eng: "colt", ua: "лоша", id: id() },
    { eng: "mare", ua: "кобила", id: id() },
    { eng: "pig", ua: "свиня", id: id() },
    { eng: "sow", ua: "самка свині", id: id() },
    { eng: "piglet", ua: "порося", id: id() },
    { eng: "rabbit", ua: "кролик", id: id() },
    { eng: "pig", ua: "свиня", id: id() },
    
  ];
  